# Generated by Django 5.0.6 on 2024-06-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='total',
            new_name='precio_total',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='cart',
        ),
        migrations.AddField(
            model_name='boleta',
            name='cantidad_productos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='boleta',
            name='productos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='BoletaProducto',
        ),
    ]
