# Generated by Django 5.0.6 on 2024-06-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproductos', '0003_remove_cartitem_precio_total_cart_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
