# Generated by Django 5.0.6 on 2024-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproductos', '0004_cart_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
